// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shorter.proto

package shorter

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ...   CREATE   ...
type UrlRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UrlRequest) Reset()         { *m = UrlRequest{} }
func (m *UrlRequest) String() string { return proto.CompactTextString(m) }
func (*UrlRequest) ProtoMessage()    {}
func (*UrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_daeaefe75edd53f9, []int{0}
}

func (m *UrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UrlRequest.Unmarshal(m, b)
}
func (m *UrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UrlRequest.Marshal(b, m, deterministic)
}
func (m *UrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UrlRequest.Merge(m, src)
}
func (m *UrlRequest) XXX_Size() int {
	return xxx_messageInfo_UrlRequest.Size(m)
}
func (m *UrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UrlRequest proto.InternalMessageInfo

func (m *UrlRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type LinkResponse struct {
	Link                 string   `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkResponse) Reset()         { *m = LinkResponse{} }
func (m *LinkResponse) String() string { return proto.CompactTextString(m) }
func (*LinkResponse) ProtoMessage()    {}
func (*LinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_daeaefe75edd53f9, []int{1}
}

func (m *LinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkResponse.Unmarshal(m, b)
}
func (m *LinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkResponse.Marshal(b, m, deterministic)
}
func (m *LinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkResponse.Merge(m, src)
}
func (m *LinkResponse) XXX_Size() int {
	return xxx_messageInfo_LinkResponse.Size(m)
}
func (m *LinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LinkResponse proto.InternalMessageInfo

func (m *LinkResponse) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

// ...   GET   ...
type LinkRequest struct {
	Link                 string   `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkRequest) Reset()         { *m = LinkRequest{} }
func (m *LinkRequest) String() string { return proto.CompactTextString(m) }
func (*LinkRequest) ProtoMessage()    {}
func (*LinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_daeaefe75edd53f9, []int{2}
}

func (m *LinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkRequest.Unmarshal(m, b)
}
func (m *LinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkRequest.Marshal(b, m, deterministic)
}
func (m *LinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkRequest.Merge(m, src)
}
func (m *LinkRequest) XXX_Size() int {
	return xxx_messageInfo_LinkRequest.Size(m)
}
func (m *LinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LinkRequest proto.InternalMessageInfo

func (m *LinkRequest) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

type UrlResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UrlResponse) Reset()         { *m = UrlResponse{} }
func (m *UrlResponse) String() string { return proto.CompactTextString(m) }
func (*UrlResponse) ProtoMessage()    {}
func (*UrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_daeaefe75edd53f9, []int{3}
}

func (m *UrlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UrlResponse.Unmarshal(m, b)
}
func (m *UrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UrlResponse.Marshal(b, m, deterministic)
}
func (m *UrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UrlResponse.Merge(m, src)
}
func (m *UrlResponse) XXX_Size() int {
	return xxx_messageInfo_UrlResponse.Size(m)
}
func (m *UrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UrlResponse proto.InternalMessageInfo

func (m *UrlResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*UrlRequest)(nil), "shorter.UrlRequest")
	proto.RegisterType((*LinkResponse)(nil), "shorter.LinkResponse")
	proto.RegisterType((*LinkRequest)(nil), "shorter.LinkRequest")
	proto.RegisterType((*UrlResponse)(nil), "shorter.UrlResponse")
}

func init() {
	proto.RegisterFile("shorter.proto", fileDescriptor_daeaefe75edd53f9)
}

var fileDescriptor_daeaefe75edd53f9 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0xce, 0xc8, 0x2f,
	0x2a, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xe4, 0xb8,
	0xb8, 0x42, 0x8b, 0x72, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x04, 0xb8, 0x98, 0x4b,
	0x8b, 0x72, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x25, 0x25, 0x2e, 0x1e, 0x9f,
	0xcc, 0xbc, 0xec, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x21, 0x2e, 0x96, 0x9c,
	0xcc, 0xbc, 0x6c, 0xa8, 0x12, 0x30, 0x5b, 0x49, 0x91, 0x8b, 0x1b, 0xa2, 0x06, 0x62, 0x08, 0x36,
	0x25, 0xf2, 0x5c, 0xdc, 0x60, 0x6b, 0xa0, 0xa6, 0x60, 0xd8, 0x63, 0x54, 0xc6, 0xc5, 0x1e, 0x0c,
	0x71, 0x92, 0x90, 0x19, 0x17, 0x9b, 0x73, 0x51, 0x6a, 0x62, 0x49, 0xaa, 0x90, 0xb0, 0x1e, 0xcc,
	0xd5, 0x08, 0x37, 0x4a, 0x89, 0xc2, 0x05, 0x91, 0x1d, 0xa6, 0xc4, 0x20, 0x64, 0xcc, 0xc5, 0xec,
	0x9e, 0x5a, 0x22, 0x24, 0x82, 0x26, 0x0f, 0xd1, 0x25, 0x82, 0x6a, 0x14, 0x4c, 0x53, 0x12, 0x1b,
	0x38, 0x3c, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x10, 0x9a, 0x19, 0x27, 0x20, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ShorterClient is the client API for Shorter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShorterClient interface {
	Create(ctx context.Context, in *UrlRequest, opts ...grpc.CallOption) (*LinkResponse, error)
	Get(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*UrlResponse, error)
}

type shorterClient struct {
	cc grpc.ClientConnInterface
}

func NewShorterClient(cc grpc.ClientConnInterface) ShorterClient {
	return &shorterClient{cc}
}

func (c *shorterClient) Create(ctx context.Context, in *UrlRequest, opts ...grpc.CallOption) (*LinkResponse, error) {
	out := new(LinkResponse)
	err := c.cc.Invoke(ctx, "/shorter.Shorter/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shorterClient) Get(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*UrlResponse, error) {
	out := new(UrlResponse)
	err := c.cc.Invoke(ctx, "/shorter.Shorter/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShorterServer is the server API for Shorter service.
type ShorterServer interface {
	Create(context.Context, *UrlRequest) (*LinkResponse, error)
	Get(context.Context, *LinkRequest) (*UrlResponse, error)
}

// UnimplementedShorterServer can be embedded to have forward compatible implementations.
type UnimplementedShorterServer struct {
}

func (*UnimplementedShorterServer) Create(ctx context.Context, req *UrlRequest) (*LinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedShorterServer) Get(ctx context.Context, req *LinkRequest) (*UrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterShorterServer(s *grpc.Server, srv ShorterServer) {
	s.RegisterService(&_Shorter_serviceDesc, srv)
}

func _Shorter_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShorterServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shorter.Shorter/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShorterServer).Create(ctx, req.(*UrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shorter_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShorterServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shorter.Shorter/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShorterServer).Get(ctx, req.(*LinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Shorter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shorter.Shorter",
	HandlerType: (*ShorterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Shorter_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Shorter_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shorter.proto",
}
