// protoc -I proto proto/shorter.proto --go_out=plugins=grpc:proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: shorter.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Url struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Url) Reset() {
	*x = Url{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shorter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Url) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url) ProtoMessage() {}

func (x *Url) ProtoReflect() protoreflect.Message {
	mi := &file_shorter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Url.ProtoReflect.Descriptor instead.
func (*Url) Descriptor() ([]byte, []int) {
	return file_shorter_proto_rawDescGZIP(), []int{0}
}

func (x *Url) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Link struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *Link) Reset() {
	*x = Link{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shorter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_shorter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_shorter_proto_rawDescGZIP(), []int{1}
}

func (x *Link) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

var File_shorter_proto protoreflect.FileDescriptor

var file_shorter_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x22, 0x17, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x22, 0x1a, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x32, 0x58, 0x0a,
	0x07, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x0c, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x72, 0x6c,
	0x1a, 0x0d, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x22,
	0x00, 0x12, 0x24, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0d, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x72, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x1a, 0x0c, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x72, 0x2e, 0x55, 0x72, 0x6c, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shorter_proto_rawDescOnce sync.Once
	file_shorter_proto_rawDescData = file_shorter_proto_rawDesc
)

func file_shorter_proto_rawDescGZIP() []byte {
	file_shorter_proto_rawDescOnce.Do(func() {
		file_shorter_proto_rawDescData = protoimpl.X.CompressGZIP(file_shorter_proto_rawDescData)
	})
	return file_shorter_proto_rawDescData
}

var file_shorter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shorter_proto_goTypes = []interface{}{
	(*Url)(nil),  // 0: shorter.Url
	(*Link)(nil), // 1: shorter.Link
}
var file_shorter_proto_depIdxs = []int32{
	0, // 0: shorter.Shorter.Create:input_type -> shorter.Url
	1, // 1: shorter.Shorter.Get:input_type -> shorter.Link
	1, // 2: shorter.Shorter.Create:output_type -> shorter.Link
	0, // 3: shorter.Shorter.Get:output_type -> shorter.Url
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shorter_proto_init() }
func file_shorter_proto_init() {
	if File_shorter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shorter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Url); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shorter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Link); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shorter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shorter_proto_goTypes,
		DependencyIndexes: file_shorter_proto_depIdxs,
		MessageInfos:      file_shorter_proto_msgTypes,
	}.Build()
	File_shorter_proto = out.File
	file_shorter_proto_rawDesc = nil
	file_shorter_proto_goTypes = nil
	file_shorter_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ShorterClient is the client API for Shorter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShorterClient interface {
	Create(ctx context.Context, in *Url, opts ...grpc.CallOption) (*Link, error)
	Get(ctx context.Context, in *Link, opts ...grpc.CallOption) (*Url, error)
}

type shorterClient struct {
	cc grpc.ClientConnInterface
}

func NewShorterClient(cc grpc.ClientConnInterface) ShorterClient {
	return &shorterClient{cc}
}

func (c *shorterClient) Create(ctx context.Context, in *Url, opts ...grpc.CallOption) (*Link, error) {
	out := new(Link)
	err := c.cc.Invoke(ctx, "/shorter.Shorter/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shorterClient) Get(ctx context.Context, in *Link, opts ...grpc.CallOption) (*Url, error) {
	out := new(Url)
	err := c.cc.Invoke(ctx, "/shorter.Shorter/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShorterServer is the server API for Shorter service.
type ShorterServer interface {
	Create(context.Context, *Url) (*Link, error)
	Get(context.Context, *Link) (*Url, error)
}

// UnimplementedShorterServer can be embedded to have forward compatible implementations.
type UnimplementedShorterServer struct {
}

func (*UnimplementedShorterServer) Create(context.Context, *Url) (*Link, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedShorterServer) Get(context.Context, *Link) (*Url, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterShorterServer(s *grpc.Server, srv ShorterServer) {
	s.RegisterService(&_Shorter_serviceDesc, srv)
}

func _Shorter_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Url)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShorterServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shorter.Shorter/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShorterServer).Create(ctx, req.(*Url))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shorter_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Link)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShorterServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shorter.Shorter/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShorterServer).Get(ctx, req.(*Link))
	}
	return interceptor(ctx, in, info, handler)
}

var _Shorter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shorter.Shorter",
	HandlerType: (*ShorterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Shorter_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Shorter_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shorter.proto",
}
